name: GenerationProductions
favicon: null
layout_spectrum: 0.281229161657393
typography_spectrum: 0.8152926366310567
title: Generation Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9156716908328235
  lightness: 0.16787991300225258
  saturation: 0.8753501463215798
  rhythmicContrast: 0.05593479564413428
purpose: []
