name: GenerationProductions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8152926366310567
title: Generation Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b4fda'
    - '#2b2b2b'
    - '#000000'
    - '#0000ff'
    - '#0080ff'
  brandStrength: 0.875
  lightness: 0.16787991300225258
  saturation: 0.8753501463215798
  rhythmicContrast: 0.25
purpose: []
