title: Generation Productions
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8753501
  brandStrength: 0.875
  lightness: 0.6761547
  brandColors:
    - '#2b4fda'
    - '#2b2b2b'
    - '#000000'
    - '#0000ff'
    - '#0080ff'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: GenerationProductions
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.52146
layout_spectrum: 0.02738989
